version: '3.4'
services:
  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./environment/pgdump:/app/
    #- pgdata:/var/lib/postgresql/data
    command: "-F -e -c full_page_writes=0 -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.max=1000 -c pg_stat_statements.track=all"
  zookeeper:
    container_name: wf-zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:1.0.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic-wf:1:1"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_DB=timeseries
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - ./server/influxdb:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    environment:
      - INFLUXDB_URL=http://172.18.0.1:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
    ports:
      - "10000:10000"
      - "8888:8888"
    volumes:
      - ./server/chronograf:/var/lib/chronograf
    links:
      - influxdb
    depends_on:
      - influxdb
      - telegraf

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    user: "0"
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ./server/grafana:/var/lib/grafana