spring:
  application:
    name: WholeFood
  kafka:
    admin:
      bootstrap-servers: '127.0.0.1:9092'
    consumer:
      bootstrap-servers: '127.0.0.1:9092'
      group-id: 'server.broadcast'
      enable-auto-commit: true

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true

logging:
  level:
    org.springframework.kafka: debug